#!/bin/bash
echo "OmnomIRC Daemon Script"
echo "======================="
while :
do
	php OmnomIRC.php
	echo "Starting up again due to crash..."
	echo "Will start up again after 30 seconds."
	sleep 30s
done

