#!/bin/bash
echo "TopicBot Daemon Script"
echo "======================="
while :
do
	php TopicBot.php
	echo "Starting up again due to crash..."
	echo "Will start up again after 30 seconds."
	sleep 30s
done

