services:
    omnimaga.OmnomIRC.listener:
        class: omnimaga\OmnomIRC\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }