services:
    omnimaga.OmnomIRC.controller:
        class: omnimaga\OmnomIRC\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    omnimaga.OmnomIRC.listener:
        class: omnimaga\OmnomIRC\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }