DROP TABLE IF EXISTS `irc_users`;
CREATE TABLE `irc_users` (  `usernum` int(11) NOT NULL AUTO_INCREMENT,  `username` varchar(45) NOT NULL,  `channel` varchar(45) NOT NULL,  `online` int(50) NOT NULL DEFAULT '0', `time` varchar(45) NOT NULL, PRIMARY KEY (`usernum`)) ENGINE=InnoDB AUTO_INCREMENT=210612849 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `irc_permissions`;
CREATE TABLE `irc_permissions` (  `generic_autoincrementing_prikey` int(11) NOT NULL AUTO_INCREMENT,  `username` varchar(120) DEFAULT NULL,  `channel` varchar(120) NOT NULL,  `modes` varchar(120) NOT NULL,  `isChanModes` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`generic_autoincrementing_prikey`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `irc_outgoing_messages`;
CREATE TABLE `irc_outgoing_messages` (  `prikey` int(11) NOT NULL AUTO_INCREMENT,  `message` varchar(1024) NOT NULL,  `nick` varchar(45) NOT NULL,  `channel` varchar(45) NOT NULL,  `action` tinyint(1) NOT NULL DEFAULT '0',`fromSource` INT(11) NOT NULL DEFAULT '0', `type` varchar(45) NOT NULL DEFAULT 'msg', PRIMARY KEY (`prikey`)) ENGINE=InnoDB AUTO_INCREMENT=6069 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `irc_lines`;
CREATE TABLE `irc_lines` (`line_number` int(10) unsigned NOT NULL AUTO_INCREMENT,  `name1` varchar(45) NOT NULL,  `name2` varchar(45) DEFAULT NULL,  `message` varchar(1024) DEFAULT NULL,  `type` varchar(45) NOT NULL,  `channel` varchar(45) NOT NULL,  `time` varchar(45) NOT NULL,  `Online` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`line_number`)) ENGINE=InnoDB AUTO_INCREMENT=126652 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `irc_topics`;
CREATE TABLE `irc_topics` (  `channum` int(11) NOT NULL AUTO_INCREMENT,  `chan` varchar(45) NOT NULL,  `topic` varchar(1024) NOT NULL,  PRIMARY KEY (`channum`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
DROP TABLE IF EXISTS `irc_userstuff`;
CREATE TABLE IF NOT EXISTS `irc_userstuff` (  `usernum` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(45) NOT NULL,  `ignores` varchar(1024) NOT NULL,  `ops` varchar(1024) NOT NULL,  `bans` varchar(1024) NOT NULL,  `kicks` varchar(1024) NOT NULL,  `globalOp` int(10) NOT NULL,  `globalBan` int(10) NOT NULL,  PRIMARY KEY (`usernum`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
